// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package blogdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BlogsBlog struct {
	BlogID            int64
	AuthorID          string
	UrlSlug           string
	Title             string
	ContentJson       []byte
	ContentText       string
	ThumbnailUrl      pgtype.Text
	TitleVector       interface{}
	ContentVector     interface{}
	Status            string
	LikeCount         int64
	DislikeCount      int64
	DailyAccessCount  int64
	WeeklyAccessCount int64
	AccessCount       int64
	IsApproved        bool
	ReportCount       int64
	CreatedAt         pgtype.Timestamptz
	CreatedBy         string
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         string
	DeletedAt         pgtype.Timestamptz
	DeletedBy         pgtype.Text
}

type BlogsBlogMetric struct {
	BlogID int64
	Date   pgtype.Date
	Views  int64
}

type BlogsBlogRanking struct {
	BlogID            int64
	RankAllTime       pgtype.Int4
	RankTrending      pgtype.Int4
	ScoreAllTime      pgtype.Float8
	ScoreTrending     pgtype.Float8
	LikeCount         int32
	DislikeCount      int32
	CommentCount      int32
	WeeklyAccessCount int32
	DailyAccessCount  int32
	CreatedAt         pgtype.Timestamptz
	ComputedAt        pgtype.Timestamptz
}

type BlogsBlogReaction struct {
	ID        uuid.UUID
	BlogID    int64
	UserID    string
	Type      string
	Status    string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type BlogsBlogRequestTracking struct {
	BlogID    int64
	RequestID string
}

type BlogsBlogTag struct {
	TagID     int64
	BlogID    int64
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type BlogsComment struct {
	ID               uuid.UUID
	BlogID           int64
	Content          string
	ActorType        string
	ActorID          pgtype.Text
	ActorDisplayName string
	ActorAvatarUrl   pgtype.Text
	Status           string
	ParentCommentID  *uuid.UUID
	RootCommentID    uuid.UUID
	LikeCount        int32
	DislikeCount     int32
	Depth            int16
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type BlogsCommentReaction struct {
	ID        uuid.UUID
	CommentID uuid.UUID
	UserID    string
	Type      string
	Status    string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type BlogsIdxUserAuthorProfile struct {
	UserID      string
	AuthorID    string
	Avatar      pgtype.Text
	Slug        string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type BlogsReport struct {
	ID              int64
	BlogID          int64
	UserID          string
	UserDisplayName string
	Reason          string
	CreatedAt       pgtype.Timestamptz
}

type BlogsTag struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
