// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package blogdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BlogsBlog struct {
	BlogID       int64
	AuthorID     string
	UrlSlug      string
	Title        string
	Content      pgtype.Text
	Status       string
	LikeCount    int32
	DislikeCount int32
	CreatedAt    pgtype.Timestamptz
	CreatedBy    string
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    string
	DeletedAt    pgtype.Timestamptz
	DeletedBy    pgtype.Text
}

type BlogsBlogReaction struct {
	ID        uuid.UUID
	BlogID    int64
	UserID    string
	Type      string
	Status    string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type BlogsBlogTag struct {
	TagID     int64
	BlogID    int64
	CreatedAt pgtype.Timestamptz
	CreatedBy string
	UpdatedAt pgtype.Timestamptz
	UpdatedBy string
	DeletedAt pgtype.Timestamptz
	DeletedBy pgtype.Text
}

type BlogsComment struct {
	ID               uuid.UUID
	BlogID           int64
	Content          string
	ActorType        string
	ActorID          pgtype.Text
	ActorDisplayName string
	ActorAvatarUrl   pgtype.Text
	Status           string
	ParentCommentID  *uuid.UUID
	RootCommentID    uuid.UUID
	Depth            int16
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type BlogsCommentReaction struct {
	ID        uuid.UUID
	CommentID uuid.UUID
	UserID    string
	Type      string
	CreatedAt pgtype.Timestamptz
}

type BlogsIdxUserAuthorProfile struct {
	UserID      string
	AuthorID    string
	Slug        string
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type BlogsTag struct {
	TagID     int64
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	CreatedBy string
	UpdatedAt pgtype.Timestamptz
	UpdatedBy string
	DeletedAt pgtype.Timestamptz
	DeletedBy pgtype.Text
}

type UsersNotification struct {
	NotificationID int64
	UserID         *uuid.UUID
	Content        []byte
	IsRead         bool
	CreatedAt      pgtype.Timestamptz
	CreatedBy      *uuid.UUID
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      *uuid.UUID
	DeletedAt      pgtype.Timestamptz
	DeletedBy      *uuid.UUID
}

type UsersRefreshToken struct {
	TokenID          uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}

type UsersUser struct {
	UserID       uuid.UUID
	Username     string
	Email        pgtype.Text
	Password     string
	Nickname     string
	FirstName    string
	LastName     string
	Role         string
	Status       pgtype.Text
	Points       int32
	TokenVersion pgtype.Int4
	LastLogout   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	CreatedBy    *uuid.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	DeletedBy    *uuid.UUID
}
