// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package blogdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BlogsBlog struct {
	BlogID    int64
	AuthorID  string
	UrlSlug   string
	Title     string
	Content   pgtype.Text
	Status    string
	CreatedAt pgtype.Timestamptz
	CreatedBy string
	UpdatedAt pgtype.Timestamptz
	UpdatedBy string
	DeletedAt pgtype.Timestamptz
	DeletedBy pgtype.Text
}

type BlogsBlogTag struct {
	TagID     int64
	BlogID    int64
	CreatedAt pgtype.Timestamptz
	CreatedBy string
	UpdatedAt pgtype.Timestamptz
	UpdatedBy string
	DeletedAt pgtype.Timestamptz
	DeletedBy pgtype.Text
}

type BlogsIdxUserAuthorProfile struct {
	UserID    string
	AuthorID  string
	CreatedAt pgtype.Timestamptz
}

type BlogsTag struct {
	TagID     int64
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	CreatedBy string
	UpdatedAt pgtype.Timestamptz
	UpdatedBy string
	DeletedAt pgtype.Timestamptz
	DeletedBy pgtype.Text
}

type UsersNotification struct {
	NotificationID int64
	UserID         *uuid.UUID
	Content        string
	IsRead         bool
	CreatedAt      pgtype.Timestamptz
	CreatedBy      *uuid.UUID
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      *uuid.UUID
	DeletedAt      pgtype.Timestamptz
	DeletedBy      *uuid.UUID
}

type UsersRefreshToken struct {
	TokenID          uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}

type UsersUser struct {
	UserID       uuid.UUID
	Username     string
	Email        pgtype.Text
	Password     string
	Nickname     string
	FirstName    string
	LastName     string
	Role         string
	Active       pgtype.Text
	Points       int32
	TokenVersion pgtype.Int4
	LastLogout   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	CreatedBy    *uuid.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	DeletedBy    *uuid.UUID
}
