// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package blogdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs.blogs(
    author_id,
    title,
    url_slug,
    content,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING blog_id, author_id, url_slug, title, content, status, like_count, dislike_count, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateBlogParams struct {
	AuthorID  string
	Title     string
	UrlSlug   string
	Content   pgtype.Text
	CreatedBy string
	UpdatedBy string
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (BlogsBlog, error) {
	row := q.db.QueryRow(ctx, createBlog,
		arg.AuthorID,
		arg.Title,
		arg.UrlSlug,
		arg.Content,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i BlogsBlog
	err := row.Scan(
		&i.BlogID,
		&i.AuthorID,
		&i.UrlSlug,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.LikeCount,
		&i.DislikeCount,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one

WITH vals AS (
    SELECT gen_random_uuid() AS u1,
            gen_random_uuid() AS u2
)
INSERT INTO blogs.comments (
    id, blog_id, content, actor_type, actor_id, actor_display_name, parent_comment_id, root_comment_id, depth
)
SELECT u1, $1, $2, $3, $4, $5, $6,
    CASE 
        WHEN $8 = 0 THEN u1 
        ELSE $7
    END AS root_comment_id, 
    $8
FROM vals
RETURNING id, blog_id, content, actor_type, actor_id, actor_display_name, actor_avatar_url, status, parent_comment_id, root_comment_id, like_count, dislike_count, depth, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	BlogID           int64
	Content          string
	ActorType        string
	ActorID          pgtype.Text
	ActorDisplayName string
	ParentCommentID  *uuid.UUID
	RootCommentID    uuid.UUID
	Depth            int16
}

// comments
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (BlogsComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.BlogID,
		arg.Content,
		arg.ActorType,
		arg.ActorID,
		arg.ActorDisplayName,
		arg.ParentCommentID,
		arg.RootCommentID,
		arg.Depth,
	)
	var i BlogsComment
	err := row.Scan(
		&i.ID,
		&i.BlogID,
		&i.Content,
		&i.ActorType,
		&i.ActorID,
		&i.ActorDisplayName,
		&i.ActorAvatarUrl,
		&i.Status,
		&i.ParentCommentID,
		&i.RootCommentID,
		&i.LikeCount,
		&i.DislikeCount,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUserAuthorProfileIDCacheRecord = `-- name: CreateUserAuthorProfileIDCacheRecord :exec
INSERT INTO blogs.idx_user_author_profile (
    user_id,
    author_id,
    slug,
    display_name
) VALUES (
    $1, $2, $3, $4
)
`

type CreateUserAuthorProfileIDCacheRecordParams struct {
	UserID      string
	AuthorID    string
	Slug        string
	DisplayName string
}

func (q *Queries) CreateUserAuthorProfileIDCacheRecord(ctx context.Context, arg CreateUserAuthorProfileIDCacheRecordParams) error {
	_, err := q.db.Exec(ctx, createUserAuthorProfileIDCacheRecord,
		arg.UserID,
		arg.AuthorID,
		arg.Slug,
		arg.DisplayName,
	)
	return err
}

const deleteAuthorCache = `-- name: DeleteAuthorCache :exec
DELETE FROM blogs.idx_user_author_profile
WHERE author_id = $1
`

func (q *Queries) DeleteAuthorCache(ctx context.Context, authorID string) error {
	_, err := q.db.Exec(ctx, deleteAuthorCache, authorID)
	return err
}

const deleteAuthorHardDeletedBlogs = `-- name: DeleteAuthorHardDeletedBlogs :exec
DELETE FROM blogs.blogs
WHERE author_id = $1
`

func (q *Queries) DeleteAuthorHardDeletedBlogs(ctx context.Context, authorID string) error {
	_, err := q.db.Exec(ctx, deleteAuthorHardDeletedBlogs, authorID)
	return err
}

const deleteBlog = `-- name: DeleteBlog :one
UPDATE blogs.blogs
    SET deleted_by = $1,
    deleted_at = NOW(),
    status = 'deleted'
WHERE blog_id = $2
RETURNING blog_id
`

type DeleteBlogParams struct {
	DeletedBy pgtype.Text
	BlogID    int64
}

func (q *Queries) DeleteBlog(ctx context.Context, arg DeleteBlogParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteBlog, arg.DeletedBy, arg.BlogID)
	var blog_id int64
	err := row.Scan(&blog_id)
	return blog_id, err
}

const deleteComment = `-- name: DeleteComment :one
UPDATE blogs.comments
SET status = 'delete', updated_at = NOW(), deleted_at = NOW()
WHERE id = $1
RETURNING COUNT(*)
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, deleteComment, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuthorCacheByUserID = `-- name: GetAuthorCacheByUserID :one
SELECT user_id, author_id, avatar, slug, display_name, status, created_at, deleted_at
FROM blogs.idx_user_author_profile
WHERE user_id = $1
`

func (q *Queries) GetAuthorCacheByUserID(ctx context.Context, userID string) (BlogsIdxUserAuthorProfile, error) {
	row := q.db.QueryRow(ctx, getAuthorCacheByUserID, userID)
	var i BlogsIdxUserAuthorProfile
	err := row.Scan(
		&i.UserID,
		&i.AuthorID,
		&i.Avatar,
		&i.Slug,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBlog = `-- name: GetBlog :one
SELECT 
    b.blog_id, 
    b.title,
    b.url_slug,
    b.author_id,
    b.content,
    b.like_count,
    b.dislike_count,
    b.status,
    b.created_at, 
    b.created_by, 
    b.updated_at, 
    b.updated_by,
    i.slug,
    i.display_name
FROM blogs.blogs b
JOIN blogs.idx_user_author_profile i ON i.author_id = b.author_id
WHERE b.blog_id = $1 AND b.deleted_at IS NULL
`

type GetBlogRow struct {
	BlogID       int64
	Title        string
	UrlSlug      string
	AuthorID     string
	Content      pgtype.Text
	LikeCount    int32
	DislikeCount int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	CreatedBy    string
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    string
	Slug         string
	DisplayName  string
}

func (q *Queries) GetBlog(ctx context.Context, blogID int64) (GetBlogRow, error) {
	row := q.db.QueryRow(ctx, getBlog, blogID)
	var i GetBlogRow
	err := row.Scan(
		&i.BlogID,
		&i.Title,
		&i.UrlSlug,
		&i.AuthorID,
		&i.Content,
		&i.LikeCount,
		&i.DislikeCount,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Slug,
		&i.DisplayName,
	)
	return i, err
}

const getBlogByUrlSlug = `-- name: GetBlogByUrlSlug :one
SELECT 
    b.blog_id, b.author_id, b.url_slug, b.title, b.content, b.status, b.like_count, b.dislike_count, b.created_at, b.created_by, b.updated_at, b.updated_by, b.deleted_at, b.deleted_by,
    i.slug,
    i.display_name,
    i.slug,
    i.display_name
FROM blogs.blogs b
JOIN blogs.idx_user_author_profile i ON i.author_id = b.author_id
WHERE b.url_slug = $1 AND b.deleted_at IS NULL
`

type GetBlogByUrlSlugRow struct {
	BlogID        int64
	AuthorID      string
	UrlSlug       string
	Title         string
	Content       pgtype.Text
	Status        string
	LikeCount     int32
	DislikeCount  int32
	CreatedAt     pgtype.Timestamptz
	CreatedBy     string
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     string
	DeletedAt     pgtype.Timestamptz
	DeletedBy     pgtype.Text
	Slug          string
	DisplayName   string
	Slug_2        string
	DisplayName_2 string
}

func (q *Queries) GetBlogByUrlSlug(ctx context.Context, urlSlug string) (GetBlogByUrlSlugRow, error) {
	row := q.db.QueryRow(ctx, getBlogByUrlSlug, urlSlug)
	var i GetBlogByUrlSlugRow
	err := row.Scan(
		&i.BlogID,
		&i.AuthorID,
		&i.UrlSlug,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.LikeCount,
		&i.DislikeCount,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Slug,
		&i.DisplayName,
		&i.Slug_2,
		&i.DisplayName_2,
	)
	return i, err
}

const getBlogRootComment = `-- name: GetBlogRootComment :many
WITH child_counts AS (
    SELECT parent_comment_id, COUNT(*) AS cnt
    FROM blogs.comments
    GROUP BY parent_comment_id
)
SELECT
    p.id, p.blog_id, p.content, p.actor_type, p.actor_id, p.actor_display_name, p.actor_avatar_url, p.status, p.parent_comment_id, p.root_comment_id, p.like_count, p.dislike_count, p.depth, p.created_at, p.updated_at, p.deleted_at,
    COALESCE(cc.cnt, 0) AS reply_count
FROM blogs.comments p
LEFT JOIN child_counts cc
    ON cc.parent_comment_id = p.id
WHERE
    p.blog_id = $1
    AND p.status <> 'hidden'
    AND p.depth = 0
`

type GetBlogRootCommentRow struct {
	ID               uuid.UUID
	BlogID           int64
	Content          string
	ActorType        string
	ActorID          pgtype.Text
	ActorDisplayName string
	ActorAvatarUrl   pgtype.Text
	Status           string
	ParentCommentID  *uuid.UUID
	RootCommentID    uuid.UUID
	LikeCount        int32
	DislikeCount     int32
	Depth            int16
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	ReplyCount       int64
}

func (q *Queries) GetBlogRootComment(ctx context.Context, blogID int64) ([]GetBlogRootCommentRow, error) {
	rows, err := q.db.Query(ctx, getBlogRootComment, blogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlogRootCommentRow
	for rows.Next() {
		var i GetBlogRootCommentRow
		if err := rows.Scan(
			&i.ID,
			&i.BlogID,
			&i.Content,
			&i.ActorType,
			&i.ActorID,
			&i.ActorDisplayName,
			&i.ActorAvatarUrl,
			&i.Status,
			&i.ParentCommentID,
			&i.RootCommentID,
			&i.LikeCount,
			&i.DislikeCount,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlogRootCommentCount = `-- name: GetBlogRootCommentCount :one
SELECT COUNT(*) AS total
FROM blogs.comments c
WHERE c.blog_id = $1
    AND c.status <> 'hidden'
`

func (q *Queries) GetBlogRootCommentCount(ctx context.Context, blogID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getBlogRootCommentCount, blogID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getBlogRootCommentWithUserReaction = `-- name: GetBlogRootCommentWithUserReaction :many
WITH child_counts AS (
    SELECT parent_comment_id, COUNT(*) AS cnt
    FROM blogs.comments
    GROUP BY parent_comment_id
)
SELECT
    p.id, p.blog_id, p.content, p.actor_type, p.actor_id, p.actor_display_name, p.actor_avatar_url, p.status, p.parent_comment_id, p.root_comment_id, p.like_count, p.dislike_count, p.depth, p.created_at, p.updated_at, p.deleted_at,
    COALESCE(cc.cnt, 0) AS reply_count,
    r.type AS reaction_type
FROM blogs.comments p
LEFT JOIN child_counts cc
    ON cc.parent_comment_id = p.id
LEFT JOIN blogs.comment_reactions r
    ON r.comment_id = p.id
    AND r.user_id = $2
WHERE
    p.blog_id = $1
    AND p.status <> 'hidden'
    AND p.depth = 0
`

type GetBlogRootCommentWithUserReactionParams struct {
	BlogID int64
	UserID string
}

type GetBlogRootCommentWithUserReactionRow struct {
	ID               uuid.UUID
	BlogID           int64
	Content          string
	ActorType        string
	ActorID          pgtype.Text
	ActorDisplayName string
	ActorAvatarUrl   pgtype.Text
	Status           string
	ParentCommentID  *uuid.UUID
	RootCommentID    uuid.UUID
	LikeCount        int32
	DislikeCount     int32
	Depth            int16
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	ReplyCount       int64
	ReactionType     pgtype.Text
}

func (q *Queries) GetBlogRootCommentWithUserReaction(ctx context.Context, arg GetBlogRootCommentWithUserReactionParams) ([]GetBlogRootCommentWithUserReactionRow, error) {
	rows, err := q.db.Query(ctx, getBlogRootCommentWithUserReaction, arg.BlogID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlogRootCommentWithUserReactionRow
	for rows.Next() {
		var i GetBlogRootCommentWithUserReactionRow
		if err := rows.Scan(
			&i.ID,
			&i.BlogID,
			&i.Content,
			&i.ActorType,
			&i.ActorID,
			&i.ActorDisplayName,
			&i.ActorAvatarUrl,
			&i.Status,
			&i.ParentCommentID,
			&i.RootCommentID,
			&i.LikeCount,
			&i.DislikeCount,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ReplyCount,
			&i.ReactionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlogWithUserReaction = `-- name: GetBlogWithUserReaction :one
SELECT 
    b.blog_id, b.author_id, b.url_slug, b.title, b.content, b.status, b.like_count, b.dislike_count, b.created_at, b.created_by, b.updated_at, b.updated_by, b.deleted_at, b.deleted_by,
    i.slug,
    i.display_name,
    r.type AS reaction_type
FROM blogs.blogs b
JOIN blogs.idx_user_author_profile i ON i.author_id = b.author_id
LEFT JOIN blogs.blog_reactions r
    ON r.blog_id = b.blog_id
    AND r.user_id = $1
WHERE b.url_slug = $2 AND b.deleted_at IS NULL
`

type GetBlogWithUserReactionParams struct {
	UserID  string
	UrlSlug string
}

type GetBlogWithUserReactionRow struct {
	BlogID       int64
	AuthorID     string
	UrlSlug      string
	Title        string
	Content      pgtype.Text
	Status       string
	LikeCount    int32
	DislikeCount int32
	CreatedAt    pgtype.Timestamptz
	CreatedBy    string
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    string
	DeletedAt    pgtype.Timestamptz
	DeletedBy    pgtype.Text
	Slug         string
	DisplayName  string
	ReactionType pgtype.Text
}

func (q *Queries) GetBlogWithUserReaction(ctx context.Context, arg GetBlogWithUserReactionParams) (GetBlogWithUserReactionRow, error) {
	row := q.db.QueryRow(ctx, getBlogWithUserReaction, arg.UserID, arg.UrlSlug)
	var i GetBlogWithUserReactionRow
	err := row.Scan(
		&i.BlogID,
		&i.AuthorID,
		&i.UrlSlug,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.LikeCount,
		&i.DislikeCount,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Slug,
		&i.DisplayName,
		&i.ReactionType,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, blog_id, content, actor_type, actor_id, actor_display_name, actor_avatar_url, status, parent_comment_id, root_comment_id, like_count, dislike_count, depth, created_at, updated_at, deleted_at
FROM blogs.comments
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (BlogsComment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i BlogsComment
	err := row.Scan(
		&i.ID,
		&i.BlogID,
		&i.Content,
		&i.ActorType,
		&i.ActorID,
		&i.ActorDisplayName,
		&i.ActorAvatarUrl,
		&i.Status,
		&i.ParentCommentID,
		&i.RootCommentID,
		&i.LikeCount,
		&i.DislikeCount,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentsByParentComment = `-- name: GetCommentsByParentComment :many
SELECT p.id, p.blog_id, p.content, p.actor_type, p.actor_id, p.actor_display_name, p.actor_avatar_url, p.status, p.parent_comment_id, p.root_comment_id, p.like_count, p.dislike_count, p.depth, p.created_at, p.updated_at, p.deleted_at,
    COUNT(c.id) AS child_comment_count
FROM blogs.comments p
LEFT JOIN blogs.comments c
    ON c.parent_comment_id = p.id   AND c.status <> 'hidden'
WHERE p.parent_comment_id = $1 AND p.status <> 'hidden'
GROUP BY p.id
`

type GetCommentsByParentCommentRow struct {
	ID                uuid.UUID
	BlogID            int64
	Content           string
	ActorType         string
	ActorID           pgtype.Text
	ActorDisplayName  string
	ActorAvatarUrl    pgtype.Text
	Status            string
	ParentCommentID   *uuid.UUID
	RootCommentID     uuid.UUID
	LikeCount         int32
	DislikeCount      int32
	Depth             int16
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	ChildCommentCount int64
}

func (q *Queries) GetCommentsByParentComment(ctx context.Context, parentCommentID *uuid.UUID) ([]GetCommentsByParentCommentRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByParentComment, parentCommentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByParentCommentRow
	for rows.Next() {
		var i GetCommentsByParentCommentRow
		if err := rows.Scan(
			&i.ID,
			&i.BlogID,
			&i.Content,
			&i.ActorType,
			&i.ActorID,
			&i.ActorDisplayName,
			&i.ActorAvatarUrl,
			&i.Status,
			&i.ParentCommentID,
			&i.RootCommentID,
			&i.LikeCount,
			&i.DislikeCount,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ChildCommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByParentCommentUserWithReaction = `-- name: GetCommentsByParentCommentUserWithReaction :many
WITH child_counts AS (
    SELECT parent_comment_id, COUNT(*) AS cnt
    FROM blogs.comments
    WHERE status <> 'hidden'
    GROUP BY parent_comment_id
)
SELECT 
    p.id, p.blog_id, p.content, p.actor_type, p.actor_id, p.actor_display_name, p.actor_avatar_url, p.status, p.parent_comment_id, p.root_comment_id, p.like_count, p.dislike_count, p.depth, p.created_at, p.updated_at, p.deleted_at,
    COALESCE(cc.cnt, 0) AS child_comment_count,
    r.type AS reaction_type
FROM blogs.comments p
LEFT JOIN child_counts cc
    ON cc.parent_comment_id = p.id
LEFT JOIN blogs.comment_reactions r
    ON r.comment_id = p.id
    AND r.user_id = $2
WHERE 
    p.parent_comment_id = $1 
    AND p.status <> 'hidden'
`

type GetCommentsByParentCommentUserWithReactionParams struct {
	ParentCommentID *uuid.UUID
	UserID          string
}

type GetCommentsByParentCommentUserWithReactionRow struct {
	ID                uuid.UUID
	BlogID            int64
	Content           string
	ActorType         string
	ActorID           pgtype.Text
	ActorDisplayName  string
	ActorAvatarUrl    pgtype.Text
	Status            string
	ParentCommentID   *uuid.UUID
	RootCommentID     uuid.UUID
	LikeCount         int32
	DislikeCount      int32
	Depth             int16
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	ChildCommentCount int64
	ReactionType      pgtype.Text
}

func (q *Queries) GetCommentsByParentCommentUserWithReaction(ctx context.Context, arg GetCommentsByParentCommentUserWithReactionParams) ([]GetCommentsByParentCommentUserWithReactionRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByParentCommentUserWithReaction, arg.ParentCommentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByParentCommentUserWithReactionRow
	for rows.Next() {
		var i GetCommentsByParentCommentUserWithReactionRow
		if err := rows.Scan(
			&i.ID,
			&i.BlogID,
			&i.Content,
			&i.ActorType,
			&i.ActorID,
			&i.ActorDisplayName,
			&i.ActorAvatarUrl,
			&i.Status,
			&i.ParentCommentID,
			&i.RootCommentID,
			&i.LikeCount,
			&i.DislikeCount,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ChildCommentCount,
			&i.ReactionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByRootComment = `-- name: GetCommentsByRootComment :many
SELECT id, blog_id, content, actor_type, actor_id, actor_display_name, actor_avatar_url, status, parent_comment_id, root_comment_id, like_count, dislike_count, depth, created_at, updated_at, deleted_at
FROM blogs.comments
WHERE root_comment_id = $1  AND status <> 'hidden'
`

func (q *Queries) GetCommentsByRootComment(ctx context.Context, rootCommentID uuid.UUID) ([]BlogsComment, error) {
	rows, err := q.db.Query(ctx, getCommentsByRootComment, rootCommentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogsComment
	for rows.Next() {
		var i BlogsComment
		if err := rows.Scan(
			&i.ID,
			&i.BlogID,
			&i.Content,
			&i.ActorType,
			&i.ActorID,
			&i.ActorDisplayName,
			&i.ActorAvatarUrl,
			&i.Status,
			&i.ParentCommentID,
			&i.RootCommentID,
			&i.LikeCount,
			&i.DislikeCount,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteBlog = `-- name: HardDeleteBlog :one
DELETE FROM blogs.blogs
WHERE blog_id = $1
RETURNING blog_id
`

func (q *Queries) HardDeleteBlog(ctx context.Context, blogID int64) (int64, error) {
	row := q.db.QueryRow(ctx, hardDeleteBlog, blogID)
	var blog_id int64
	err := row.Scan(&blog_id)
	return blog_id, err
}

const hideComment = `-- name: HideComment :one
UPDATE blogs.comments
SET status = 'hide', updated_at = NOW()
WHERE id = $1
RETURNING COUNT(*)
`

func (q *Queries) HideComment(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, hideComment, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllBlogs = `-- name: ListAllBlogs :many
SELECT blog_id, title, content, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM blogs.blogs
`

type ListAllBlogsRow struct {
	BlogID    int64
	Title     string
	Content   pgtype.Text
	CreatedAt pgtype.Timestamptz
	CreatedBy string
	UpdatedAt pgtype.Timestamptz
	UpdatedBy string
	DeletedAt pgtype.Timestamptz
	DeletedBy pgtype.Text
}

func (q *Queries) ListAllBlogs(ctx context.Context) ([]ListAllBlogsRow, error) {
	rows, err := q.db.Query(ctx, listAllBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllBlogsRow
	for rows.Next() {
		var i ListAllBlogsRow
		if err := rows.Scan(
			&i.BlogID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogs = `-- name: ListBlogs :many
SELECT 
    b.blog_id,
    b.author_id,
    b.title, 
    b.url_slug,
    b.content,
    b.like_count,
    b.dislike_count, 
    b.status,
    b.created_at, 
    b.created_by, 
    b.updated_at, 
    b.updated_by,
    i.slug,
    i.display_name
FROM blogs.blogs b
JOIN blogs.idx_user_author_profile i ON i.author_id = b.author_id
WHERE b.deleted_at IS NULL
`

type ListBlogsRow struct {
	BlogID       int64
	AuthorID     string
	Title        string
	UrlSlug      string
	Content      pgtype.Text
	LikeCount    int32
	DislikeCount int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	CreatedBy    string
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    string
	Slug         string
	DisplayName  string
}

func (q *Queries) ListBlogs(ctx context.Context) ([]ListBlogsRow, error) {
	rows, err := q.db.Query(ctx, listBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogsRow
	for rows.Next() {
		var i ListBlogsRow
		if err := rows.Scan(
			&i.BlogID,
			&i.AuthorID,
			&i.Title,
			&i.UrlSlug,
			&i.Content,
			&i.LikeCount,
			&i.DislikeCount,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Slug,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogsByAuthor = `-- name: ListBlogsByAuthor :many
SELECT
    b.blog_id, 
    b.title,
    b.url_slug,
    b.author_id,
    b.content,
    b.like_count,
    b.dislike_count,
    b.status,
    b.created_at, 
    b.created_by, 
    b.updated_at, 
    b.updated_by,
    i.slug,
    i.display_name
FROM blogs.blogs b
JOIN blogs.idx_user_author_profile i ON i.author_id = b.author_id
WHERE i.author_id = $1 AND b.deleted_at IS NULL AND b.status = $2
`

type ListBlogsByAuthorParams struct {
	AuthorID string
	Status   string
}

type ListBlogsByAuthorRow struct {
	BlogID       int64
	Title        string
	UrlSlug      string
	AuthorID     string
	Content      pgtype.Text
	LikeCount    int32
	DislikeCount int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	CreatedBy    string
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    string
	Slug         string
	DisplayName  string
}

func (q *Queries) ListBlogsByAuthor(ctx context.Context, arg ListBlogsByAuthorParams) ([]ListBlogsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listBlogsByAuthor, arg.AuthorID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogsByAuthorRow
	for rows.Next() {
		var i ListBlogsByAuthorRow
		if err := rows.Scan(
			&i.BlogID,
			&i.Title,
			&i.UrlSlug,
			&i.AuthorID,
			&i.Content,
			&i.LikeCount,
			&i.DislikeCount,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Slug,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogsByAuthorSlug = `-- name: ListBlogsByAuthorSlug :many
SELECT
    b.blog_id, 
    b.title,
    b.url_slug,
    b.author_id,
    b.content,
    b.status,
    b.created_at, 
    b.created_by, 
    b.updated_at, 
    b.updated_by,
    i.slug,
    i.display_name
FROM blogs.blogs b
JOIN blogs.idx_user_author_profile i ON i.author_id = b.author_id
WHERE i.slug = $1 AND b.deleted_at IS NULL AND b.status = $2
`

type ListBlogsByAuthorSlugParams struct {
	Slug   string
	Status string
}

type ListBlogsByAuthorSlugRow struct {
	BlogID      int64
	Title       string
	UrlSlug     string
	AuthorID    string
	Content     pgtype.Text
	Status      string
	CreatedAt   pgtype.Timestamptz
	CreatedBy   string
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   string
	Slug        string
	DisplayName string
}

func (q *Queries) ListBlogsByAuthorSlug(ctx context.Context, arg ListBlogsByAuthorSlugParams) ([]ListBlogsByAuthorSlugRow, error) {
	rows, err := q.db.Query(ctx, listBlogsByAuthorSlug, arg.Slug, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogsByAuthorSlugRow
	for rows.Next() {
		var i ListBlogsByAuthorSlugRow
		if err := rows.Scan(
			&i.BlogID,
			&i.Title,
			&i.UrlSlug,
			&i.AuthorID,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Slug,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuthorCacheAsDeleted = `-- name: MarkAuthorCacheAsDeleted :exec
UPDATE blogs.idx_user_author_profile
SET status = 'deleted', deleted_at = NOW()
WHERE author_id = $1
`

func (q *Queries) MarkAuthorCacheAsDeleted(ctx context.Context, authorID string) error {
	_, err := q.db.Exec(ctx, markAuthorCacheAsDeleted, authorID)
	return err
}

const restoreBlog = `-- name: RestoreBlog :exec
UPDATE blogs.blogs
SET status = $1,
deleted_at = null,
deleted_by = null
WHERE blog_id = $2
`

type RestoreBlogParams struct {
	Status string
	BlogID int64
}

func (q *Queries) RestoreBlog(ctx context.Context, arg RestoreBlogParams) error {
	_, err := q.db.Exec(ctx, restoreBlog, arg.Status, arg.BlogID)
	return err
}

const syncBlogLikeAndDislike = `-- name: SyncBlogLikeAndDislike :exec
UPDATE blogs.blogs b
SET
    like_count = COALESCE(x.like_count, 0),
    dislike_count = COALESCE(x.dislike_count, 0)
FROM (
    SELECT
        blog_id,
        COUNT(*) FILTER (WHERE type = 'like' AND status = 'active') AS like_count,
        COUNT(*) FILTER (WHERE type = 'dislike' AND status = 'active') AS dislike_count
    FROM blogs.blog_reactions
    GROUP BY blog_id
) x
WHERE x.blog_id = b.blog_id
`

func (q *Queries) SyncBlogLikeAndDislike(ctx context.Context) error {
	_, err := q.db.Exec(ctx, syncBlogLikeAndDislike)
	return err
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE blogs.blogs
    SET title = $1,
    content = $2
WHERE blog_id = $3
RETURNING blog_id
`

type UpdateBlogParams struct {
	Title   string
	Content pgtype.Text
	BlogID  int64
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateBlog, arg.Title, arg.Content, arg.BlogID)
	var blog_id int64
	err := row.Scan(&blog_id)
	return blog_id, err
}

const updateBlogReactionCount = `-- name: UpdateBlogReactionCount :exec
UPDATE blogs.blogs
    SET like_count = like_count + $1,
    dislike_count = dislike_count + $2
WHERE blog_id = $3
`

type UpdateBlogReactionCountParams struct {
	LikeCount    int32
	DislikeCount int32
	BlogID       int64
}

func (q *Queries) UpdateBlogReactionCount(ctx context.Context, arg UpdateBlogReactionCountParams) error {
	_, err := q.db.Exec(ctx, updateBlogReactionCount, arg.LikeCount, arg.DislikeCount, arg.BlogID)
	return err
}

const updateBlogReactionType = `-- name: UpdateBlogReactionType :exec
UPDATE blogs.blog_reactions
    SET type = $1
WHERE id = $2
`

type UpdateBlogReactionTypeParams struct {
	Type string
	ID   uuid.UUID
}

func (q *Queries) UpdateBlogReactionType(ctx context.Context, arg UpdateBlogReactionTypeParams) error {
	_, err := q.db.Exec(ctx, updateBlogReactionType, arg.Type, arg.ID)
	return err
}

const updateBlogStatusForDeletedAuthor = `-- name: UpdateBlogStatusForDeletedAuthor :exec
UPDATE blogs.blogs
SET status = 'author_deleted',
deleted_at = NOW()
WHERE blogs.author_id = $1
`

func (q *Queries) UpdateBlogStatusForDeletedAuthor(ctx context.Context, authorID string) error {
	_, err := q.db.Exec(ctx, updateBlogStatusForDeletedAuthor, authorID)
	return err
}

const updateCommentReactionCount = `-- name: UpdateCommentReactionCount :exec
UPDATE blogs.comments
    SET like_count = like_count + $1,
    dislike_count = dislike_count + $2
WHERE id = $3
`

type UpdateCommentReactionCountParams struct {
	LikeCount    int32
	DislikeCount int32
	ID           uuid.UUID
}

func (q *Queries) UpdateCommentReactionCount(ctx context.Context, arg UpdateCommentReactionCountParams) error {
	_, err := q.db.Exec(ctx, updateCommentReactionCount, arg.LikeCount, arg.DislikeCount, arg.ID)
	return err
}

const upsertBlogReaction = `-- name: UpsertBlogReaction :one
WITH existing AS (
    SELECT type
    FROM blogs.blog_reactions e
    WHERE e.blog_id = $1 AND e.user_id = $2
    FOR UPDATE
),
upsert AS (
    INSERT INTO blogs.blog_reactions (blog_id, user_id, type)
    VALUES ($1, $2, $3)
    ON CONFLICT (blog_id, user_id)
    DO UPDATE SET type = EXCLUDED.type
    RETURNING type AS new_type
)
SELECT
    COALESCE((SELECT type FROM existing), 'none')::VARCHAR(20) AS old_type,
    (SELECT new_type FROM upsert)::VARCHAR(20) AS new_type
`

type UpsertBlogReactionParams struct {
	BlogID int64
	UserID string
	Type   string
}

type UpsertBlogReactionRow struct {
	OldType string
	NewType string
}

func (q *Queries) UpsertBlogReaction(ctx context.Context, arg UpsertBlogReactionParams) (UpsertBlogReactionRow, error) {
	row := q.db.QueryRow(ctx, upsertBlogReaction, arg.BlogID, arg.UserID, arg.Type)
	var i UpsertBlogReactionRow
	err := row.Scan(&i.OldType, &i.NewType)
	return i, err
}

const upsertCommentReaction = `-- name: UpsertCommentReaction :one
WITH existing AS (
    SELECT type
    FROM blogs.comment_reactions e
    WHERE e.comment_id = $1 AND e.user_id = $2
    FOR UPDATE
),
upsert AS (
    INSERT INTO blogs.comment_reactions (comment_id, user_id, type)
    VALUES ($1, $2, $3)
    ON CONFLICT (comment_id, user_id)
    DO UPDATE SET type = EXCLUDED.type
    RETURNING type AS new_type
)
SELECT
    COALESCE((SELECT type FROM existing), 'none')::VARCHAR(20) AS old_type,
    COALESCE((SELECT new_type FROM upsert), 'none')::VARCHAR(20) AS new_type
`

type UpsertCommentReactionParams struct {
	CommentID uuid.UUID
	UserID    string
	Type      string
}

type UpsertCommentReactionRow struct {
	OldType string
	NewType string
}

func (q *Queries) UpsertCommentReaction(ctx context.Context, arg UpsertCommentReactionParams) (UpsertCommentReactionRow, error) {
	row := q.db.QueryRow(ctx, upsertCommentReaction, arg.CommentID, arg.UserID, arg.Type)
	var i UpsertCommentReactionRow
	err := row.Scan(&i.OldType, &i.NewType)
	return i, err
}

const verifyAuthorIDByUserID = `-- name: VerifyAuthorIDByUserID :one
SELECT author_id
FROM blogs.idx_user_author_profile
WHERE user_id = $1
`

func (q *Queries) VerifyAuthorIDByUserID(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, verifyAuthorIDByUserID, userID)
	var author_id string
	err := row.Scan(&author_id)
	return author_id, err
}
