// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package blogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs.blogs(
    author_id,
    title,
    url_slug,
    content,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING blog_id, author_id, url_slug, title, content, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateBlogParams struct {
	AuthorID  string
	Title     string
	UrlSlug   string
	Content   pgtype.Text
	CreatedBy string
	UpdatedBy string
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (BlogsBlog, error) {
	row := q.db.QueryRow(ctx, createBlog,
		arg.AuthorID,
		arg.Title,
		arg.UrlSlug,
		arg.Content,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i BlogsBlog
	err := row.Scan(
		&i.BlogID,
		&i.AuthorID,
		&i.UrlSlug,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const createUserAuthorProfileIDCacheRecord = `-- name: CreateUserAuthorProfileIDCacheRecord :exec
INSERT INTO blogs.idx_user_author_profile (
    user_id,
    author_id
) VALUES (
    $1, $2
)
`

type CreateUserAuthorProfileIDCacheRecordParams struct {
	UserID   string
	AuthorID string
}

func (q *Queries) CreateUserAuthorProfileIDCacheRecord(ctx context.Context, arg CreateUserAuthorProfileIDCacheRecordParams) error {
	_, err := q.db.Exec(ctx, createUserAuthorProfileIDCacheRecord, arg.UserID, arg.AuthorID)
	return err
}

const deleteBlog = `-- name: DeleteBlog :one
UPDATE blogs.blogs
    SET deleted_by = $1,
    deleted_at = NOW()
WHERE blog_id = $2
RETURNING blog_id
`

type DeleteBlogParams struct {
	DeletedBy pgtype.Text
	BlogID    int64
}

func (q *Queries) DeleteBlog(ctx context.Context, arg DeleteBlogParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteBlog, arg.DeletedBy, arg.BlogID)
	var blog_id int64
	err := row.Scan(&blog_id)
	return blog_id, err
}

const getBlog = `-- name: GetBlog :one
SELECT 
    b.blog_id, 
    b.title,
    b.url_slug,
    b.author_id,
    CONCAT(u.first_name, ' ', u.last_name) as author_name,
    u.nickname,
    u.email,
    b.content,
    b.status,
    b.created_at, 
    b.created_by, 
    b.updated_at, 
    b.updated_by 
FROM blogs.blogs b
JOIN users.users u ON u.user_id = b.author_id
WHERE b.blog_id = $1 AND b.deleted_at IS NULL
`

type GetBlogRow struct {
	BlogID     int64
	Title      string
	UrlSlug    string
	AuthorID   string
	AuthorName interface{}
	Nickname   string
	Email      pgtype.Text
	Content    pgtype.Text
	Status     string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  string
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  string
}

func (q *Queries) GetBlog(ctx context.Context, blogID int64) (GetBlogRow, error) {
	row := q.db.QueryRow(ctx, getBlog, blogID)
	var i GetBlogRow
	err := row.Scan(
		&i.BlogID,
		&i.Title,
		&i.UrlSlug,
		&i.AuthorID,
		&i.AuthorName,
		&i.Nickname,
		&i.Email,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getBlogByUrlSlug = `-- name: GetBlogByUrlSlug :one
SELECT 
    b.blog_id, 
    b.title,
    b.url_slug,
    b.author_id,
    CONCAT(u.first_name, ' ', u.last_name) as author_name,
    u.nickname,
    u.email,
    b.content,
    b.status,
    b.created_at, 
    b.created_by, 
    b.updated_at, 
    b.updated_by 
FROM blogs.blogs b
JOIN users.users u ON u.user_id = b.author_id
WHERE b.url_slug = $1 AND b.deleted_at IS NULL
`

type GetBlogByUrlSlugRow struct {
	BlogID     int64
	Title      string
	UrlSlug    string
	AuthorID   string
	AuthorName interface{}
	Nickname   string
	Email      pgtype.Text
	Content    pgtype.Text
	Status     string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  string
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  string
}

func (q *Queries) GetBlogByUrlSlug(ctx context.Context, urlSlug string) (GetBlogByUrlSlugRow, error) {
	row := q.db.QueryRow(ctx, getBlogByUrlSlug, urlSlug)
	var i GetBlogByUrlSlugRow
	err := row.Scan(
		&i.BlogID,
		&i.Title,
		&i.UrlSlug,
		&i.AuthorID,
		&i.AuthorName,
		&i.Nickname,
		&i.Email,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const hardDeleteBlog = `-- name: HardDeleteBlog :one
DELETE FROM blogs.blogs
WHERE blog_id = $1
RETURNING blog_id
`

func (q *Queries) HardDeleteBlog(ctx context.Context, blogID int64) (int64, error) {
	row := q.db.QueryRow(ctx, hardDeleteBlog, blogID)
	var blog_id int64
	err := row.Scan(&blog_id)
	return blog_id, err
}

const listAllBlogs = `-- name: ListAllBlogs :many
SELECT blog_id, title, content, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM blogs.blogs
`

type ListAllBlogsRow struct {
	BlogID    int64
	Title     string
	Content   pgtype.Text
	CreatedAt pgtype.Timestamptz
	CreatedBy string
	UpdatedAt pgtype.Timestamptz
	UpdatedBy string
	DeletedAt pgtype.Timestamptz
	DeletedBy pgtype.Text
}

func (q *Queries) ListAllBlogs(ctx context.Context) ([]ListAllBlogsRow, error) {
	rows, err := q.db.Query(ctx, listAllBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllBlogsRow
	for rows.Next() {
		var i ListAllBlogsRow
		if err := rows.Scan(
			&i.BlogID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogs = `-- name: ListBlogs :many
SELECT 
    b.blog_id,
    b.author_id,
    b.title, 
    b.url_slug,
    b.content, 
    b.status,
    b.created_at, 
    b.created_by, 
    b.updated_at, 
    b.updated_by 
FROM blogs.blogs b
WHERE b.deleted_at IS NULL
`

type ListBlogsRow struct {
	BlogID    int64
	AuthorID  string
	Title     string
	UrlSlug   string
	Content   pgtype.Text
	Status    string
	CreatedAt pgtype.Timestamptz
	CreatedBy string
	UpdatedAt pgtype.Timestamptz
	UpdatedBy string
}

func (q *Queries) ListBlogs(ctx context.Context) ([]ListBlogsRow, error) {
	rows, err := q.db.Query(ctx, listBlogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogsRow
	for rows.Next() {
		var i ListBlogsRow
		if err := rows.Scan(
			&i.BlogID,
			&i.AuthorID,
			&i.Title,
			&i.UrlSlug,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogsByAuthor = `-- name: ListBlogsByAuthor :many
SELECT
    b.blog_id, 
    b.title,
    b.url_slug,
    b.author_id,
    u.nickname,
    CONCAT(u.first_name, ' ', u.last_name) as author_name,
    u.email,
    b.content,
    b.status,
    b.created_at, 
    b.created_by, 
    b.updated_at, 
    b.updated_by 
FROM blogs.blogs b
JOIN users.users u ON u.user_id = b.author_id
WHERE b.author_id = $1 AND b.deleted_at IS NULL AND b.status = $2
`

type ListBlogsByAuthorParams struct {
	AuthorID string
	Status   string
}

type ListBlogsByAuthorRow struct {
	BlogID     int64
	Title      string
	UrlSlug    string
	AuthorID   string
	Nickname   string
	AuthorName interface{}
	Email      pgtype.Text
	Content    pgtype.Text
	Status     string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  string
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  string
}

func (q *Queries) ListBlogsByAuthor(ctx context.Context, arg ListBlogsByAuthorParams) ([]ListBlogsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listBlogsByAuthor, arg.AuthorID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogsByAuthorRow
	for rows.Next() {
		var i ListBlogsByAuthorRow
		if err := rows.Scan(
			&i.BlogID,
			&i.Title,
			&i.UrlSlug,
			&i.AuthorID,
			&i.Nickname,
			&i.AuthorName,
			&i.Email,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogsByAuthorNickname = `-- name: ListBlogsByAuthorNickname :many
SELECT
    b.blog_id, 
    b.title,
    b.url_slug,
    b.author_id,
    u.nickname,
    CONCAT(u.first_name, ' ', u.last_name) as author_name,
    u.email,
    b.content,
    b.status,
    b.created_at, 
    b.created_by, 
    b.updated_at, 
    b.updated_by 
FROM blogs.blogs b
JOIN users.users u ON u.user_id = b.author_id
WHERE u.nickname = $1 AND b.deleted_at IS NULL AND b.status = $2
`

type ListBlogsByAuthorNicknameParams struct {
	Nickname string
	Status   string
}

type ListBlogsByAuthorNicknameRow struct {
	BlogID     int64
	Title      string
	UrlSlug    string
	AuthorID   string
	Nickname   string
	AuthorName interface{}
	Email      pgtype.Text
	Content    pgtype.Text
	Status     string
	CreatedAt  pgtype.Timestamptz
	CreatedBy  string
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  string
}

func (q *Queries) ListBlogsByAuthorNickname(ctx context.Context, arg ListBlogsByAuthorNicknameParams) ([]ListBlogsByAuthorNicknameRow, error) {
	rows, err := q.db.Query(ctx, listBlogsByAuthorNickname, arg.Nickname, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogsByAuthorNicknameRow
	for rows.Next() {
		var i ListBlogsByAuthorNicknameRow
		if err := rows.Scan(
			&i.BlogID,
			&i.Title,
			&i.UrlSlug,
			&i.AuthorID,
			&i.Nickname,
			&i.AuthorName,
			&i.Email,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE blogs.blogs
    SET title = $1,
    content = $2
WHERE blog_id = $3
RETURNING blog_id
`

type UpdateBlogParams struct {
	Title   string
	Content pgtype.Text
	BlogID  int64
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateBlog, arg.Title, arg.Content, arg.BlogID)
	var blog_id int64
	err := row.Scan(&blog_id)
	return blog_id, err
}

const verifyAuthorIDByUserID = `-- name: VerifyAuthorIDByUserID :one
SELECT author_id
FROM blogs.idx_user_author_profile
WHERE user_id = $1
`

func (q *Queries) VerifyAuthorIDByUserID(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, verifyAuthorIDByUserID, userID)
	var author_id string
	err := row.Scan(&author_id)
	return author_id, err
}
