// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package blogdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BlogsBlog struct {
	BlogID    int64
	AuthorID  uuid.UUID
	Title     string
	Content   pgtype.Text
	Active    string
	CreatedAt pgtype.Timestamptz
	CreatedBy *uuid.UUID
	UpdatedAt pgtype.Timestamptz
	UpdatedBy *uuid.UUID
	DeletedAt pgtype.Timestamptz
	DeletedBy *uuid.UUID
}

type BlogsBlogTag struct {
	TagID     int64
	BlogID    int64
	CreatedAt pgtype.Timestamptz
	CreatedBy *uuid.UUID
	UpdatedAt pgtype.Timestamptz
	UpdatedBy *uuid.UUID
	DeletedAt pgtype.Timestamptz
	DeletedBy *uuid.UUID
}

type BlogsTag struct {
	TagID     int64
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	CreatedBy *uuid.UUID
	UpdatedAt pgtype.Timestamptz
	UpdatedBy *uuid.UUID
	DeletedAt pgtype.Timestamptz
	DeletedBy *uuid.UUID
}

type UsersRefreshToken struct {
	TokenID          uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}

type UsersUser struct {
	UserID       uuid.UUID
	Username     string
	Email        pgtype.Text
	Password     string
	FirstName    string
	LastName     string
	Role         string
	Active       pgtype.Text
	Points       int32
	TokenVersion pgtype.Int4
	LastLogout   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	CreatedBy    *uuid.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	DeletedBy    *uuid.UUID
}
