// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package userdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UsersNotification struct {
	NotificationID int64
	UserID         *uuid.UUID
	Content        string
	IsRead         bool
	CreatedAt      pgtype.Timestamptz
	CreatedBy      *uuid.UUID
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      *uuid.UUID
	DeletedAt      pgtype.Timestamptz
	DeletedBy      *uuid.UUID
}

type UsersRefreshToken struct {
	TokenID          uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}

type UsersUser struct {
	UserID       uuid.UUID
	Username     string
	Email        pgtype.Text
	Password     string
	Nickname     string
	FirstName    string
	LastName     string
	Role         string
	Active       pgtype.Text
	Points       int32
	TokenVersion pgtype.Int4
	LastLogout   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	CreatedBy    *uuid.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	DeletedBy    *uuid.UUID
}
