// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package userdb

import (
	"context"
)

// iteratorForCreateNotifications implements pgx.CopyFromSource.
type iteratorForCreateNotifications struct {
	rows                 []CreateNotificationsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateNotifications) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateNotifications) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].Content,
		r.rows[0].CreatedBy,
	}, nil
}

func (r iteratorForCreateNotifications) Err() error {
	return nil
}

func (q *Queries) CreateNotifications(ctx context.Context, arg []CreateNotificationsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"users", "notifications"}, []string{"user_id", "content", "created_by"}, &iteratorForCreateNotifications{rows: arg})
}
