// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package userdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserWithEmail = `-- name: CountUserWithEmail :one
SELECT COUNT(*)
FROM users.users u
WHERE u.username = $1
`

func (q *Queries) CountUserWithEmail(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserWithEmail, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO users.notifications (
    user_id,
    content,
    created_by,
    updated_by
)
VALUES ($1, $2, $3, $3)
RETURNING notification_id, user_id, content, is_read, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateNotificationParams struct {
	UserID    *uuid.UUID
	Content   []byte
	CreatedBy *uuid.UUID
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (UsersNotification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.UserID, arg.Content, arg.CreatedBy)
	var i UsersNotification
	err := row.Scan(
		&i.NotificationID,
		&i.UserID,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

type CreateNotificationsParams struct {
	UserID    *uuid.UUID
	Content   []byte
	CreatedBy *uuid.UUID
}

const createUser = `-- name: CreateUser :one
INSERT INTO users.users(
    username, 
    password, 
    first_name, 
    last_name,
    active,
    role
) VALUES (
    $1, $2, $3, $4, 'normal', $5
)
RETURNING user_id, username, email, password, nickname, first_name, last_name, role, status, points, token_version, last_logout, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateUserParams struct {
	Username  string
	Password  string
	FirstName string
	LastName  string
	Role      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UsersUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Role,
	)
	var i UsersUser
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Nickname,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.Points,
		&i.TokenVersion,
		&i.LastLogout,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users.users
WHERE user_id = $1
RETURNING user_id
`

func (q *Queries) DeleteUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteUser, userID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getDeletedUserByID = `-- name: GetDeletedUserByID :one
SELECT 
    user_id, 
    username, 
    password, 
    first_name, 
    last_name, 
    created_at, 
    created_by, 
    updated_at, 
    updated_by,
    deleted_at,
    deleted_by
FROM users.users 
WHERE user_id = $1
`

type GetDeletedUserByIDRow struct {
	UserID    uuid.UUID
	Username  string
	Password  string
	FirstName string
	LastName  string
	CreatedAt pgtype.Timestamptz
	CreatedBy *uuid.UUID
	UpdatedAt pgtype.Timestamptz
	UpdatedBy *uuid.UUID
	DeletedAt pgtype.Timestamptz
	DeletedBy *uuid.UUID
}

func (q *Queries) GetDeletedUserByID(ctx context.Context, userID uuid.UUID) (GetDeletedUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getDeletedUserByID, userID)
	var i GetDeletedUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    user_id, username, email, password, nickname, first_name, last_name, role, status, points, token_version, last_logout, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
FROM users.users 
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (UsersUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i UsersUser
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Nickname,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.Points,
		&i.TokenVersion,
		&i.LastLogout,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, email, password, nickname, first_name, last_name, role, status, points, token_version, last_logout, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
FROM users.users u
WHERE
    u.username = $1
    AND u.active <> 'banned' 
    AND u.deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (UsersUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i UsersUser
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Nickname,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.Points,
		&i.TokenVersion,
		&i.LastLogout,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getUserNotiticationsByID = `-- name: GetUserNotiticationsByID :many
SELECT n.notification_id, n.user_id, n.content, n.is_read, n.created_at, n.created_by, n.updated_at, n.updated_by, n.deleted_at, n.deleted_by
FROM users.users u
JOIN users.notifications n ON n.user_id = u.user_id
WHERE n.deleted_at IS NULL
`

func (q *Queries) GetUserNotiticationsByID(ctx context.Context) ([]UsersNotification, error) {
	rows, err := q.db.Query(ctx, getUserNotiticationsByID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersNotification
	for rows.Next() {
		var i UsersNotification
		if err := rows.Scan(
			&i.NotificationID,
			&i.UserID,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT 
    user_id, 
    username, 
    password, 
    first_name, 
    last_name, 
    created_at, 
    created_by, 
    updated_at, 
    updated_by 
FROM users.users
WHERE deleted_at IS NULL
`

type ListUsersRow struct {
	UserID    uuid.UUID
	Username  string
	Password  string
	FirstName string
	LastName  string
	CreatedAt pgtype.Timestamptz
	CreatedBy *uuid.UUID
	UpdatedAt pgtype.Timestamptz
	UpdatedBy *uuid.UUID
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithDeleteUserUsers = `-- name: ListWithDeleteUserUsers :many
SELECT user_id, username, password, first_name, last_name, created_at, created_by, updated_at, updated_by FROM users.users
`

type ListWithDeleteUserUsersRow struct {
	UserID    uuid.UUID
	Username  string
	Password  string
	FirstName string
	LastName  string
	CreatedAt pgtype.Timestamptz
	CreatedBy *uuid.UUID
	UpdatedAt pgtype.Timestamptz
	UpdatedBy *uuid.UUID
}

func (q *Queries) ListWithDeleteUserUsers(ctx context.Context) ([]ListWithDeleteUserUsersRow, error) {
	rows, err := q.db.Query(ctx, listWithDeleteUserUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWithDeleteUserUsersRow
	for rows.Next() {
		var i ListWithDeleteUserUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserAsDeleted = `-- name: MarkUserAsDeleted :exec
UPDATE users.users
SET status = 'deleted',
    updated_at = NOW(),
    updated_by = $1,
    deleted_at = NOW(),
    deleted_by = $1
WHERE users.user_id = $2
`

type MarkUserAsDeletedParams struct {
	UpdatedBy *uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) MarkUserAsDeleted(ctx context.Context, arg MarkUserAsDeletedParams) error {
	_, err := q.db.Exec(ctx, markUserAsDeleted, arg.UpdatedBy, arg.UserID)
	return err
}

const restoreUserByID = `-- name: RestoreUserByID :exec
UPDATE users.users
SET status = $1,
    updated_at = NOW(),
    updated_by = $2,
    deleted_at = NULL,
    deleted_by = NULL
WHERE users.user_id = $3
`

type RestoreUserByIDParams struct {
	Status    pgtype.Text
	UpdatedBy *uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RestoreUserByID(ctx context.Context, arg RestoreUserByIDParams) error {
	_, err := q.db.Exec(ctx, restoreUserByID, arg.Status, arg.UpdatedBy, arg.UserID)
	return err
}

const updateLastLogout = `-- name: UpdateLastLogout :exec
UPDATE users.users
    SET last_logout = NOW(),
    token_version = token_version + 1,
    updated_at = NOW(),
    updated_by = user_id
WHERE user_id = $1
`

func (q *Queries) UpdateLastLogout(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogout, userID)
	return err
}

const updateNotification = `-- name: UpdateNotification :exec
UPDATE users.notifications 
    SET is_read = $2,
    updated_at = NOW(),
    updated_by = $3
WHERE notification_id = $1
`

type UpdateNotificationParams struct {
	NotificationID int64
	IsRead         bool
	UpdatedBy      *uuid.UUID
}

func (q *Queries) UpdateNotification(ctx context.Context, arg UpdateNotificationParams) error {
	_, err := q.db.Exec(ctx, updateNotification, arg.NotificationID, arg.IsRead, arg.UpdatedBy)
	return err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE users.notifications
    SET is_read = $1,
    updated_at = NOW(),
    updated_by = $2
WHERE notification_id = ANY($3::int[])
`

type UpdateNotificationStatusParams struct {
	IsRead    bool
	UpdatedBy *uuid.UUID
	Ids       []int32
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationStatus, arg.IsRead, arg.UpdatedBy, arg.Ids)
	return err
}

const updateUserData = `-- name: UpdateUserData :one
UPDATE users.users
    SET first_name = $1, 
    last_name = $2,
    updated_at = NOW(),
    updated_by = $3
WHERE user_id = $4
RETURNING user_id
`

type UpdateUserDataParams struct {
	FirstName string
	LastName  string
	UpdatedBy *uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UpdateUserData(ctx context.Context, arg UpdateUserDataParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUserData,
		arg.FirstName,
		arg.LastName,
		arg.UpdatedBy,
		arg.UserID,
	)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users.users
    SET email = $1,
    updated_at = NOW(),
    updated_by = $3
WHERE user_id = $2
RETURNING user_id
`

type UpdateUserEmailParams struct {
	Email     pgtype.Text
	UserID    uuid.UUID
	UpdatedBy *uuid.UUID
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.Email, arg.UserID, arg.UpdatedBy)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users.users
    SET password = $1,
    updated_at = NOW(),
    updated_by = $3
WHERE user_id = $2
RETURNING user_id
`

type UpdateUserPasswordParams struct {
	Password  string
	UserID    uuid.UUID
	UpdatedBy *uuid.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.Password, arg.UserID, arg.UpdatedBy)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
