// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package outboxdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxDeadLetterQueue struct {
	ID        uuid.UUID
	SagaID    *uuid.UUID
	StepIndex pgtype.Int4
	EventType string
	Payload   []byte
	Error     string
	FailedAt  pgtype.Timestamptz
}

type OutboxOutboxEvent struct {
	ID          uuid.UUID
	SagaID      *uuid.UUID
	EventType   string
	Payload     []byte
	RetryCount  int32
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}
