// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package outboxdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxOutboxEvent struct {
	ID          uuid.UUID
	SagaID      *uuid.UUID
	EventType   string
	Context     []byte
	Payload     []byte
	Error       pgtype.Text
	RetryCount  int32
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}
