// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package outboxdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxOutboxEvent struct {
	ID          int64
	Topic       string
	Payload     []byte
	Retries     int32
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}
