// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package outboxdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUnprocessedEvent = `-- name: GetUnprocessedEvent :many
SELECT id, saga_id, event_type, context, payload, error, retry_count, created_at, processed_at
FROM outbox.outbox_events
WHERE processed_at IS NULL AND retry_count < 3
ORDER BY created_at
LIMIT 50
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetUnprocessedEvent(ctx context.Context) ([]OutboxOutboxEvent, error) {
	rows, err := q.db.Query(ctx, getUnprocessedEvent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxOutboxEvent
	for rows.Next() {
		var i OutboxOutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.SagaID,
			&i.EventType,
			&i.Context,
			&i.Payload,
			&i.Error,
			&i.RetryCount,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRecord = `-- name: InsertRecord :exec
INSERT INTO outbox.outbox_events
    (saga_id, event_type, payload, retry_count, context, error)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRecordParams struct {
	SagaID     *uuid.UUID
	EventType  string
	Payload    []byte
	RetryCount int32
	Context    []byte
	Error      pgtype.Text
}

func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) error {
	_, err := q.db.Exec(ctx, insertRecord,
		arg.SagaID,
		arg.EventType,
		arg.Payload,
		arg.RetryCount,
		arg.Context,
		arg.Error,
	)
	return err
}

const updateProcessedAt = `-- name: UpdateProcessedAt :exec
UPDATE outbox.outbox_events
    SET processed_at = NOW()
WHERE id = ANY($1::UUID[])
`

func (q *Queries) UpdateProcessedAt(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateProcessedAt, dollar_1)
	return err
}

const updateRetiresInBatch = `-- name: UpdateRetiresInBatch :exec
UPDATE outbox.outbox_events
SET retry_count = retry_count + 1
WHERE id = ANY($1::UUID[])
`

func (q *Queries) UpdateRetiresInBatch(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateRetiresInBatch, dollar_1)
	return err
}
