// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package outboxdb

import (
	"context"
)

const getUnprocessedEvent = `-- name: GetUnprocessedEvent :many
SELECT id, event_type, payload
FROM outbox.outbox_events
WHERE processed_at IS NULL
ORDER BY created_at
LIMIT 50
FOR UPDATE SKIP LOCKED
`

type GetUnprocessedEventRow struct {
	ID        int64
	EventType string
	Payload   []byte
}

func (q *Queries) GetUnprocessedEvent(ctx context.Context) ([]GetUnprocessedEventRow, error) {
	rows, err := q.db.Query(ctx, getUnprocessedEvent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnprocessedEventRow
	for rows.Next() {
		var i GetUnprocessedEventRow
		if err := rows.Scan(&i.ID, &i.EventType, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRecord = `-- name: InsertRecord :exec
INSERT INTO outbox.outbox_events
        (aggregate_type, aggregate_id, event_type, payload)
VALUES ($1,$2,$3,$4)
`

type InsertRecordParams struct {
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       []byte
}

func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) error {
	_, err := q.db.Exec(ctx, insertRecord,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const updateProcessedAt = `-- name: UpdateProcessedAt :exec
UPDATE outbox.outbox_events
    SET processed_at = NOW()
WHERE id = ANY($1::bigint[])
`

func (q *Queries) UpdateProcessedAt(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, updateProcessedAt, dollar_1)
	return err
}
