// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package commondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserTokenVersionByID = `-- name: GetUserTokenVersionByID :one
SELECT u.token_version
FROM users.users u
WHERE u.user_id = $1
`

func (q *Queries) GetUserTokenVersionByID(ctx context.Context, userID uuid.UUID) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getUserTokenVersionByID, userID)
	var token_version pgtype.Int4
	err := row.Scan(&token_version)
	return token_version, err
}
