// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sagadb

import (
	"context"
)

// iteratorForCreateSagaSteps implements pgx.CopyFromSource.
type iteratorForCreateSagaSteps struct {
	rows                 []CreateSagaStepsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSagaSteps) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSagaSteps) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SagaID,
		r.rows[0].StepIndex,
		r.rows[0].StepName,
		r.rows[0].Status,
		r.rows[0].RetryCount,
		r.rows[0].MaxRetries,
		r.rows[0].NextRetryAt,
		r.rows[0].Context,
	}, nil
}

func (r iteratorForCreateSagaSteps) Err() error {
	return nil
}

func (q *Queries) CreateSagaSteps(ctx context.Context, arg []CreateSagaStepsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"saga", "saga_steps"}, []string{"saga_id", "step_index", "step_name", "status", "retry_count", "max_retries", "next_retry_at", "context"}, &iteratorForCreateSagaSteps{rows: arg})
}
