// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sagadb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SagaDeadLetterQueue struct {
	ID            uuid.UUID
	SagaID        uuid.UUID
	StepIndex     int32
	StepName      string
	Status        string
	EventID       uuid.UUID
	RetryCount    int32
	NextRetryAt   pgtype.Timestamptz
	Input         []byte
	Output        []byte
	LastError     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	CompensatedAt pgtype.Timestamptz
	Error         string
	FailedAt      pgtype.Timestamptz
}

type SagaSaga struct {
	ID          uuid.UUID
	SagaType    string
	Status      string
	CurrentStep int32
	Context     []byte
	Error       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SagaSagaStep struct {
	ID            uuid.UUID
	SagaID        uuid.UUID
	StepIndex     int32
	StepName      string
	Status        string
	EventID       uuid.UUID
	RetryCount    int32
	NextRetryAt   pgtype.Timestamptz
	Input         []byte
	Output        []byte
	LastError     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	CompensatedAt pgtype.Timestamptz
}
