// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sagadb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SagaSaga struct {
	ID          uuid.UUID
	SagaType    string
	Status      string
	CurrentStep pgtype.Text
	Payload     []byte
	Context     []byte
	Error       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SagaSagaStep struct {
	ID            uuid.UUID
	SagaID        *uuid.UUID
	StepIndex     int32
	StepName      string
	Status        string
	RetryCount    int32
	MaxRetries    int32
	NextRetryAt   pgtype.Timestamptz
	Context       []byte
	LastError     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	CompensatedAt pgtype.Timestamptz
}
