// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sagadb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSaga = `-- name: CreateSaga :one
INSERT INTO saga.sagas (
  saga_type, status, current_step, payload, context, error
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type CreateSagaParams struct {
	SagaType    string
	Status      string
	CurrentStep pgtype.Text
	Payload     []byte
	Context     []byte
	Error       pgtype.Text
}

func (q *Queries) CreateSaga(ctx context.Context, arg CreateSagaParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSaga,
		arg.SagaType,
		arg.Status,
		arg.CurrentStep,
		arg.Payload,
		arg.Context,
		arg.Error,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

type CreateSagaStepsParams struct {
	SagaID      *uuid.UUID
	StepIndex   int32
	StepName    string
	Status      string
	RetryCount  int32
	MaxRetries  int32
	NextRetryAt pgtype.Timestamptz
	Context     []byte
}

const markSagaAsFailed = `-- name: MarkSagaAsFailed :exec
UPDATE saga.sagas
SET status = 'failed'
WHERE id = $1
`

func (q *Queries) MarkSagaAsFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSagaAsFailed, id)
	return err
}

const updateSaga = `-- name: UpdateSaga :exec
UPDATE saga.sagas
SET current_step = current_step + 1
WHERE id = $1
`

func (q *Queries) UpdateSaga(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSaga, id)
	return err
}

const updateStepRetries = `-- name: UpdateStepRetries :exec
UPDATE saga.saga_steps
SET 
  retry_count = retry_count + 1,
  last_error = $1,
  next_retry_at = NOW() + INTERVAL '5 seconds'
WHERE saga_id = $2 AND step_index = $3
`

type UpdateStepRetriesParams struct {
	LastError pgtype.Text
	SagaID    *uuid.UUID
	StepIndex int32
}

func (q *Queries) UpdateStepRetries(ctx context.Context, arg UpdateStepRetriesParams) error {
	_, err := q.db.Exec(ctx, updateStepRetries, arg.LastError, arg.SagaID, arg.StepIndex)
	return err
}

const updateStepStatus = `-- name: UpdateStepStatus :exec
UPDATE saga.saga_steps
SET status = 'completed'
WHERE saga_id = $1 AND step_index = $2
`

type UpdateStepStatusParams struct {
	SagaID    *uuid.UUID
	StepIndex int32
}

func (q *Queries) UpdateStepStatus(ctx context.Context, arg UpdateStepStatusParams) error {
	_, err := q.db.Exec(ctx, updateStepStatus, arg.SagaID, arg.StepIndex)
	return err
}
