// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package authordb

import (
	"context"
)

// iteratorForCreateAuthorFeatureBlogs implements pgx.CopyFromSource.
type iteratorForCreateAuthorFeatureBlogs struct {
	rows                 []CreateAuthorFeatureBlogsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateAuthorFeatureBlogs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateAuthorFeatureBlogs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AuthorID,
		r.rows[0].BlogID,
		r.rows[0].Position,
	}, nil
}

func (r iteratorForCreateAuthorFeatureBlogs) Err() error {
	return nil
}

func (q *Queries) CreateAuthorFeatureBlogs(ctx context.Context, arg []CreateAuthorFeatureBlogsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"authors", "author_featured_blogs"}, []string{"author_id", "blog_id", "position"}, &iteratorForCreateAuthorFeatureBlogs{rows: arg})
}
