// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authordb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorsAuthor struct {
	AuthorID      string
	UserID        string
	DisplayName   string
	Bio           pgtype.Text
	Avatar        pgtype.Text
	Slug          string
	SocialLink    pgtype.Text
	Status        string
	Email         pgtype.Text
	FollowerCount pgtype.Int4
	BlogCount     pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	CreatedBy     string
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     string
	DeletedAt     pgtype.Timestamptz
	DeletedBy     string
}

type AuthorsAuthorFeaturedBlog struct {
	ID        int64
	AuthorID  string
	BlogID    string
	Position  int32
	CreatedAt pgtype.Timestamp
}

type AuthorsAuthorFollower struct {
	ID        int64
	AuthorID  string
	UserID    string
	CreatedAt pgtype.Timestamptz
}

type AuthorsAuthorProfile struct {
	AuthorID   string
	TwitterUrl pgtype.Text
	GithubUrl  pgtype.Text
	WebsiteUrl pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type UsersNotification struct {
	NotificationID int64
	UserID         *uuid.UUID
	Content        string
	IsRead         bool
	CreatedAt      pgtype.Timestamptz
	CreatedBy      *uuid.UUID
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      *uuid.UUID
	DeletedAt      pgtype.Timestamptz
	DeletedBy      *uuid.UUID
}

type UsersRefreshToken struct {
	TokenID          uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}

type UsersUser struct {
	UserID       uuid.UUID
	Username     string
	Email        pgtype.Text
	Password     string
	Nickname     string
	FirstName    string
	LastName     string
	Role         string
	Active       pgtype.Text
	Points       int32
	TokenVersion pgtype.Int4
	LastLogout   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	CreatedBy    *uuid.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    *uuid.UUID
	DeletedAt    pgtype.Timestamptz
	DeletedBy    *uuid.UUID
}
