// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package authordb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreateAuthorFeatureBlogsParams struct {
	AuthorID string
	BlogID   string
	Position int32
}

const createAuthorFollower = `-- name: CreateAuthorFollower :exec
INSERT INTO authors.author_followers (
    author_id,
    user_id
) VALUES (
    $1, $2
)
`

type CreateAuthorFollowerParams struct {
	AuthorID string
	UserID   string
}

func (q *Queries) CreateAuthorFollower(ctx context.Context, arg CreateAuthorFollowerParams) error {
	_, err := q.db.Exec(ctx, createAuthorFollower, arg.AuthorID, arg.UserID)
	return err
}

const createAuthorProfile = `-- name: CreateAuthorProfile :exec
INSERT INTO authors.authors (
    author_id,
    user_id,
    display_name,
    bio,
    avatar,
    slug,
    social_link,
    status,
    email,

    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, 
    $10, $10
)
`

type CreateAuthorProfileParams struct {
	AuthorID    string
	UserID      string
	DisplayName string
	Bio         pgtype.Text
	Avatar      pgtype.Text
	Slug        string
	SocialLink  pgtype.Text
	Status      string
	Email       pgtype.Text
	CreatedBy   string
}

func (q *Queries) CreateAuthorProfile(ctx context.Context, arg CreateAuthorProfileParams) error {
	_, err := q.db.Exec(ctx, createAuthorProfile,
		arg.AuthorID,
		arg.UserID,
		arg.DisplayName,
		arg.Bio,
		arg.Avatar,
		arg.Slug,
		arg.SocialLink,
		arg.Status,
		arg.Email,
		arg.CreatedBy,
	)
	return err
}

const deleteAuthorFollower = `-- name: DeleteAuthorFollower :exec
DELETE FROM authors.author_followers
WHERE author_id = $1 AND  user_id = $2
`

type DeleteAuthorFollowerParams struct {
	AuthorID string
	UserID   string
}

func (q *Queries) DeleteAuthorFollower(ctx context.Context, arg DeleteAuthorFollowerParams) error {
	_, err := q.db.Exec(ctx, deleteAuthorFollower, arg.AuthorID, arg.UserID)
	return err
}

const deleteAuthorProfile = `-- name: DeleteAuthorProfile :exec
DELETE FROM authors.authors
WHERE author_id = $1
`

func (q *Queries) DeleteAuthorProfile(ctx context.Context, authorID string) error {
	_, err := q.db.Exec(ctx, deleteAuthorProfile, authorID)
	return err
}

const getAuthorFeatureBlogIDs = `-- name: GetAuthorFeatureBlogIDs :many
SELECT blog_id
FROM authors.author_featured_blogs f
JOIN authors.authors a ON author_id
WHERE a.slug = $1 AND a.status = $2
`

type GetAuthorFeatureBlogIDsParams struct {
	Slug   string
	Status string
}

func (q *Queries) GetAuthorFeatureBlogIDs(ctx context.Context, arg GetAuthorFeatureBlogIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getAuthorFeatureBlogIDs, arg.Slug, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var blog_id string
		if err := rows.Scan(&blog_id); err != nil {
			return nil, err
		}
		items = append(items, blog_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorFollowers = `-- name: GetAuthorFollowers :many
SELECT f.user_id
FROM authors.author_followers f
JOIN authors.authors a ON a.author_id = f.author_id
WHERE a.slug = $1
ORDER BY a.created_at
`

func (q *Queries) GetAuthorFollowers(ctx context.Context, slug string) ([]string, error) {
	rows, err := q.db.Query(ctx, getAuthorFollowers, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorFollowersByID = `-- name: GetAuthorFollowersByID :many
SELECT f.user_id
FROM authors.author_followers f
JOIN authors.authors a ON a.author_id = f.author_id
WHERE a.author_id = $1
ORDER BY a.created_at
`

func (q *Queries) GetAuthorFollowersByID(ctx context.Context, authorID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getAuthorFollowersByID, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorProfileByID = `-- name: GetAuthorProfileByID :one
SELECT author_id, user_id, display_name, bio, avatar, slug, social_link, status, email, follower_count, blog_count, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
FROM authors.authors a
WHERE a.author_id = $1 
    AND a.status = $2 
    AND ($3 = 'check_null' AND deleted_at IS NULL)
    OR ($3 = 'check_not_null' AND deleted_at IS NOT NULL)
`

type GetAuthorProfileByIDParams struct {
	AuthorID string
	Status   string
	Column3  interface{}
}

func (q *Queries) GetAuthorProfileByID(ctx context.Context, arg GetAuthorProfileByIDParams) (AuthorsAuthor, error) {
	row := q.db.QueryRow(ctx, getAuthorProfileByID, arg.AuthorID, arg.Status, arg.Column3)
	var i AuthorsAuthor
	err := row.Scan(
		&i.AuthorID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.Avatar,
		&i.Slug,
		&i.SocialLink,
		&i.Status,
		&i.Email,
		&i.FollowerCount,
		&i.BlogCount,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getAuthorProfileBySlug = `-- name: GetAuthorProfileBySlug :one
SELECT author_id, user_id, display_name, bio, avatar, slug, social_link, status, email, follower_count, blog_count, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
FROM authors.authors a
WHERE a.slug = $1 
    AND a.status = $2 
    AND ($3 = 'check_null' AND deleted_at IS NULL)
    OR ($3 = 'check_not_null' AND deleted_at IS NOT NULL)
`

type GetAuthorProfileBySlugParams struct {
	Slug    string
	Status  string
	Column3 interface{}
}

func (q *Queries) GetAuthorProfileBySlug(ctx context.Context, arg GetAuthorProfileBySlugParams) (AuthorsAuthor, error) {
	row := q.db.QueryRow(ctx, getAuthorProfileBySlug, arg.Slug, arg.Status, arg.Column3)
	var i AuthorsAuthor
	err := row.Scan(
		&i.AuthorID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.Avatar,
		&i.Slug,
		&i.SocialLink,
		&i.Status,
		&i.Email,
		&i.FollowerCount,
		&i.BlogCount,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getFollowedAuthors = `-- name: GetFollowedAuthors :many
SELECT author_id
FROM authors.author_followers
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetFollowedAuthors(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getFollowedAuthors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var author_id string
		if err := rows.Scan(&author_id); err != nil {
			return nil, err
		}
		items = append(items, author_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorProfies = `-- name: ListAuthorProfies :many
SELECT author_id, user_id, display_name, bio, avatar, slug, social_link, status, email, follower_count, blog_count, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
FROM authors.authors a
WHERE a.status = $1
    AND ($2 = 'check_null' AND deleted_at IS NULL)
    OR ($2 = 'check_not_null' AND deleted_at IS NOT NULL)
`

type ListAuthorProfiesParams struct {
	Status  string
	Column2 interface{}
}

func (q *Queries) ListAuthorProfies(ctx context.Context, arg ListAuthorProfiesParams) ([]AuthorsAuthor, error) {
	rows, err := q.db.Query(ctx, listAuthorProfies, arg.Status, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorsAuthor
	for rows.Next() {
		var i AuthorsAuthor
		if err := rows.Scan(
			&i.AuthorID,
			&i.UserID,
			&i.DisplayName,
			&i.Bio,
			&i.Avatar,
			&i.Slug,
			&i.SocialLink,
			&i.Status,
			&i.Email,
			&i.FollowerCount,
			&i.BlogCount,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuthorFollowersDeletedByUserID = `-- name: MarkAuthorFollowersDeletedByUserID :exec
UPDATE authors.author_followers
SET deleted_at = NOW()
WHERE user_id = $1
`

func (q *Queries) MarkAuthorFollowersDeletedByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAuthorFollowersDeletedByUserID, userID)
	return err
}

const restoreAuthorFollowersByUserID = `-- name: RestoreAuthorFollowersByUserID :exec
UPDATE authors.author_followers
SET deleted_at = NULL
WHERE user_id = $1
`

func (q *Queries) RestoreAuthorFollowersByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, restoreAuthorFollowersByUserID, userID)
	return err
}

const updateAuthorBlogCount = `-- name: UpdateAuthorBlogCount :exec
UPDATE authors.authors
SET blog_count = blog_count + $1
WHERE author_id = $2
`

type UpdateAuthorBlogCountParams struct {
	BlogCount pgtype.Int4
	AuthorID  string
}

func (q *Queries) UpdateAuthorBlogCount(ctx context.Context, arg UpdateAuthorBlogCountParams) error {
	_, err := q.db.Exec(ctx, updateAuthorBlogCount, arg.BlogCount, arg.AuthorID)
	return err
}

const updateAuthorFollowerCount = `-- name: UpdateAuthorFollowerCount :exec
UPDATE authors.authors
SET follower_count = follower_count + $1
WHERE author_id = $2
`

type UpdateAuthorFollowerCountParams struct {
	FollowerCount pgtype.Int4
	AuthorID      string
}

func (q *Queries) UpdateAuthorFollowerCount(ctx context.Context, arg UpdateAuthorFollowerCountParams) error {
	_, err := q.db.Exec(ctx, updateAuthorFollowerCount, arg.FollowerCount, arg.AuthorID)
	return err
}

const updateAuthorProfileBasic = `-- name: UpdateAuthorProfileBasic :exec
UPDATE authors.authors
    SET display_name = $1,
    bio = $2,
    avatar = $3,
    social_link = $4,
    updated_at = NOW(),
    updated_by = $5
WHERE author_id = $6
`

type UpdateAuthorProfileBasicParams struct {
	DisplayName string
	Bio         pgtype.Text
	Avatar      pgtype.Text
	SocialLink  pgtype.Text
	UpdatedBy   string
	AuthorID    string
}

func (q *Queries) UpdateAuthorProfileBasic(ctx context.Context, arg UpdateAuthorProfileBasicParams) error {
	_, err := q.db.Exec(ctx, updateAuthorProfileBasic,
		arg.DisplayName,
		arg.Bio,
		arg.Avatar,
		arg.SocialLink,
		arg.UpdatedBy,
		arg.AuthorID,
	)
	return err
}

const updateAuthorProfileDeleteAt = `-- name: UpdateAuthorProfileDeleteAt :exec
UPDATE authors.authors
    SET status = $1,
    updated_at = NOW(),
    updated_by = $2,
    deleted_at = NOW(),
    deleted_by = $2
WHERE author_id = $3
`

type UpdateAuthorProfileDeleteAtParams struct {
	Status    string
	UpdatedBy string
	AuthorID  string
}

func (q *Queries) UpdateAuthorProfileDeleteAt(ctx context.Context, arg UpdateAuthorProfileDeleteAtParams) error {
	_, err := q.db.Exec(ctx, updateAuthorProfileDeleteAt, arg.Status, arg.UpdatedBy, arg.AuthorID)
	return err
}

const updateAuthorProfileEmail = `-- name: UpdateAuthorProfileEmail :exec
UPDATE authors.authors
    SET email = $1,
    updated_at = NOW(),
    updated_by = $2
WHERE author_id = $3
`

type UpdateAuthorProfileEmailParams struct {
	Email     pgtype.Text
	UpdatedBy string
	AuthorID  string
}

func (q *Queries) UpdateAuthorProfileEmail(ctx context.Context, arg UpdateAuthorProfileEmailParams) error {
	_, err := q.db.Exec(ctx, updateAuthorProfileEmail, arg.Email, arg.UpdatedBy, arg.AuthorID)
	return err
}

const updateAuthorSlug = `-- name: UpdateAuthorSlug :exec
UPDATE authors.authors
SET slug = $1,
updated_at = NOW(),
updated_by = $2
WHERE author_id = $3
`

type UpdateAuthorSlugParams struct {
	Slug      string
	UpdatedBy string
	AuthorID  string
}

func (q *Queries) UpdateAuthorSlug(ctx context.Context, arg UpdateAuthorSlugParams) error {
	_, err := q.db.Exec(ctx, updateAuthorSlug, arg.Slug, arg.UpdatedBy, arg.AuthorID)
	return err
}

const updateAuthorStatus = `-- name: UpdateAuthorStatus :exec
UPDATE authors.authors
    SET status = $1::varchar(50),
    updated_at = NOW(),
    updated_by = $2,
    deleted_at = CASE
        WHEN $1::varchar(50) = 'deleted' THEN NOW()
        ELSE deleted_at
    END,
    deleted_by = CASE
        WHEN $1::varchar(50) = 'deleted' AND deleted_by IS NULL THEN $2
        ELSE deleted_by
    END
WHERE author_id = $3
`

type UpdateAuthorStatusParams struct {
	Column1   string
	UpdatedBy string
	AuthorID  string
}

func (q *Queries) UpdateAuthorStatus(ctx context.Context, arg UpdateAuthorStatusParams) error {
	_, err := q.db.Exec(ctx, updateAuthorStatus, arg.Column1, arg.UpdatedBy, arg.AuthorID)
	return err
}
