// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package authordb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthorProfile = `-- name: CreateAuthorProfile :exec
INSERT INTO authors.authors (
    author_id,
    user_id,
    display_name,
    bio,
    avatar,
    slug,
    social_link,
    status,
    email,

    created_at,
    created_by,
    updated_at,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), $9, NOW(), $10
)
`

type CreateAuthorProfileParams struct {
	AuthorID    string
	UserID      *uuid.UUID
	DisplayName string
	Bio         pgtype.Text
	Avatar      pgtype.Text
	Slug        string
	SocialLink  pgtype.Text
	Status      string
	Email       pgtype.Text
	UpdatedBy   *uuid.UUID
}

func (q *Queries) CreateAuthorProfile(ctx context.Context, arg CreateAuthorProfileParams) error {
	_, err := q.db.Exec(ctx, createAuthorProfile,
		arg.AuthorID,
		arg.UserID,
		arg.DisplayName,
		arg.Bio,
		arg.Avatar,
		arg.Slug,
		arg.SocialLink,
		arg.Status,
		arg.Email,
		arg.UpdatedBy,
	)
	return err
}

const deleteAuthorProfile = `-- name: DeleteAuthorProfile :exec
DELETE FROM authors.authors
WHERE author_id = $1
`

func (q *Queries) DeleteAuthorProfile(ctx context.Context, authorID string) error {
	_, err := q.db.Exec(ctx, deleteAuthorProfile, authorID)
	return err
}

const findAuthorProfileBySlug = `-- name: FindAuthorProfileBySlug :one
SELECT author_id, user_id, display_name, bio, avatar, slug, social_link, status, email, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
FROM authors.authors a
WHERE a.slug = $1 
    AND a.status = $2 
    AND ($3 = 'check_null' AND deleted_at IS NULL)
    OR ($3 = 'check_not_null' AND deleted_at IS NOT NULL)
`

type FindAuthorProfileBySlugParams struct {
	Slug    string
	Status  string
	Column3 interface{}
}

func (q *Queries) FindAuthorProfileBySlug(ctx context.Context, arg FindAuthorProfileBySlugParams) (AuthorsAuthor, error) {
	row := q.db.QueryRow(ctx, findAuthorProfileBySlug, arg.Slug, arg.Status, arg.Column3)
	var i AuthorsAuthor
	err := row.Scan(
		&i.AuthorID,
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.Avatar,
		&i.Slug,
		&i.SocialLink,
		&i.Status,
		&i.Email,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listAuthorProfies = `-- name: ListAuthorProfies :many
SELECT author_id, user_id, display_name, bio, avatar, slug, social_link, status, email, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
FROM authors.authors a
WHERE a.status = $1
    AND ($2 = 'check_null' AND deleted_at IS NULL)
    OR ($2 = 'check_not_null' AND deleted_at IS NOT NULL)
`

type ListAuthorProfiesParams struct {
	Status  string
	Column2 interface{}
}

func (q *Queries) ListAuthorProfies(ctx context.Context, arg ListAuthorProfiesParams) ([]AuthorsAuthor, error) {
	rows, err := q.db.Query(ctx, listAuthorProfies, arg.Status, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorsAuthor
	for rows.Next() {
		var i AuthorsAuthor
		if err := rows.Scan(
			&i.AuthorID,
			&i.UserID,
			&i.DisplayName,
			&i.Bio,
			&i.Avatar,
			&i.Slug,
			&i.SocialLink,
			&i.Status,
			&i.Email,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthorProfileBasic = `-- name: UpdateAuthorProfileBasic :exec
UPDATE authors.authors
    SET display_name = $1,
    bio = $2,
    avatar = $3,
    social_link = $4,
    updated_at = NOW(),
    updated_by = $5
WHERE author_id = $6
`

type UpdateAuthorProfileBasicParams struct {
	DisplayName string
	Bio         pgtype.Text
	Avatar      pgtype.Text
	SocialLink  pgtype.Text
	UpdatedBy   *uuid.UUID
	AuthorID    string
}

func (q *Queries) UpdateAuthorProfileBasic(ctx context.Context, arg UpdateAuthorProfileBasicParams) error {
	_, err := q.db.Exec(ctx, updateAuthorProfileBasic,
		arg.DisplayName,
		arg.Bio,
		arg.Avatar,
		arg.SocialLink,
		arg.UpdatedBy,
		arg.AuthorID,
	)
	return err
}

const updateAuthorProfileDeleteAt = `-- name: UpdateAuthorProfileDeleteAt :exec
UPDATE authors.authors
    SET status = $1,
    updated_at = NOW(),
    updated_by = $2,
    deleted_at = NOW(),
    deleted_by = $2
WHERE author_id = $3
`

type UpdateAuthorProfileDeleteAtParams struct {
	Status    string
	UpdatedBy *uuid.UUID
	AuthorID  string
}

func (q *Queries) UpdateAuthorProfileDeleteAt(ctx context.Context, arg UpdateAuthorProfileDeleteAtParams) error {
	_, err := q.db.Exec(ctx, updateAuthorProfileDeleteAt, arg.Status, arg.UpdatedBy, arg.AuthorID)
	return err
}

const updateAuthorProfileEmail = `-- name: UpdateAuthorProfileEmail :exec
UPDATE authors.authors
    SET email = $1,
    updated_at = NOW(),
    updated_by = $2
WHERE author_id = $3
`

type UpdateAuthorProfileEmailParams struct {
	Email     pgtype.Text
	UpdatedBy *uuid.UUID
	AuthorID  string
}

func (q *Queries) UpdateAuthorProfileEmail(ctx context.Context, arg UpdateAuthorProfileEmailParams) error {
	_, err := q.db.Exec(ctx, updateAuthorProfileEmail, arg.Email, arg.UpdatedBy, arg.AuthorID)
	return err
}

const updateAuthorStatus = `-- name: UpdateAuthorStatus :exec
UPDATE authors.authors
    SET status = $1,
    updated_at = NOW(),
    updated_by = $2
WHERE author_id = $3
`

type UpdateAuthorStatusParams struct {
	Status    string
	UpdatedBy *uuid.UUID
	AuthorID  string
}

func (q *Queries) UpdateAuthorStatus(ctx context.Context, arg UpdateAuthorStatusParams) error {
	_, err := q.db.Exec(ctx, updateAuthorStatus, arg.Status, arg.UpdatedBy, arg.AuthorID)
	return err
}
